# Generated by Django 5.1.15 on 2026-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_mensagem_fontes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='nota',
            field=models.IntegerField(blank=True, help_text='Nota de 1 a 5, ou 1 para Like e -1 para Dislike', null=True),
        ),
    ]
