# Generated by Django 5.1.15 on 2026-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_mensagem_comentario_mensagem_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
